// AUTH USER TYPES
export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const RESET_AUTH_FAIL = 'RESET_AUTH_FAIL';

// USER TYPES
export const SET_USER_INFO = 'SET_USER_INFO';
export const RESET_USER = 'RESET_USER';

// EMPLOYEE TYPES
export const ADD_NEW_EMPLOYEE = 'ADD_NEW_EMPLOYEE';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const REMOVE_EMPLOYEE = 'REMOVE_EMPLOYEE';
export const SELECT_EMPLOYEE = 'SELECT_EMPLOYEE';
export const UN_SELECT_EMPLOYEE = 'UN_SELECT_EMPLOYEE';

// TASKS TYPES
export const CREATE_TASK = 'CREATE_TASK';
export const DELETE_TASK = 'DELETE_TASK';

// CONTACTS TYPES
export const ADD_NEW_CONTACT = 'ADD_NEW_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const REMOVE_CONTACT = 'REMOVE_CONTACT';
export const SELECT_CONTACT = 'SELECT_CONTACT';
export const UN_SELECT_CONTACT = 'UN_SELECT_CONTACT';